<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="dcterms.date" content="2025-08-04">
<meta name="description" content="Summer 2025 research at Whitman College — imaging the vibration modes of a metal hemisphere, a viola, and a drumhead with electronic speckle pattern interferometry.">

<title>Visualizing Resonant Modes with Time-Averaged ESPI – Takahiro Hikida</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-64a204ab8560d761af7679ceaba22944.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-bd2fbcf52716fee708c0453c73363b80.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@4/tex-chtml.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../styles.css">
</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">Takahiro Hikida</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../projects.html"> 
<span class="menu-text">Projects</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../about.html"> 
<span class="menu-text">About</span></a>
  </li>  
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/takahiro-h16"> <i class="bi bi-github" role="img" aria-label="GitHub">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#abstract" id="toc-abstract" class="nav-link active" data-scroll-target="#abstract">Abstract</a></li>
  <li><a href="#background-and-objectives" id="toc-background-and-objectives" class="nav-link" data-scroll-target="#background-and-objectives">1. Background and Objectives</a></li>
  <li><a href="#experimental-setup-and-system-characterization" id="toc-experimental-setup-and-system-characterization" class="nav-link" data-scroll-target="#experimental-setup-and-system-characterization">2. Experimental Setup and System Characterization</a>
  <ul class="collapse">
  <li><a href="#optical-layout" id="toc-optical-layout" class="nav-link" data-scroll-target="#optical-layout">2.1 Optical layout</a></li>
  <li><a href="#coherence-length" id="toc-coherence-length" class="nav-link" data-scroll-target="#coherence-length">2.2 Coherence length</a></li>
  <li><a href="#piezo-calibration" id="toc-piezo-calibration" class="nav-link" data-scroll-target="#piezo-calibration">2.3 Piezo calibration</a></li>
  <li><a href="#choosing-the-piezo-drive" id="toc-choosing-the-piezo-drive" class="nav-link" data-scroll-target="#choosing-the-piezo-drive">2.4 Choosing the piezo drive</a></li>
  </ul></li>
  <li><a href="#results" id="toc-results" class="nav-link" data-scroll-target="#results">3. Results</a>
  <ul class="collapse">
  <li><a href="#metal-hemisphere" id="toc-metal-hemisphere" class="nav-link" data-scroll-target="#metal-hemisphere">3.1 Metal hemisphere</a></li>
  <li><a href="#viola" id="toc-viola" class="nav-link" data-scroll-target="#viola">3.2 Viola</a></li>
  <li><a href="#drumhead" id="toc-drumhead" class="nav-link" data-scroll-target="#drumhead">3.3 Drumhead</a></li>
  <li><a href="#piano-soundboard-preliminary" id="toc-piano-soundboard-preliminary" class="nav-link" data-scroll-target="#piano-soundboard-preliminary">3.4 Piano soundboard (preliminary)</a></li>
  </ul></li>
  <li><a href="#discussion" id="toc-discussion" class="nav-link" data-scroll-target="#discussion">4. Discussion</a></li>
  <li><a href="#future-work" id="toc-future-work" class="nav-link" data-scroll-target="#future-work">5. Future Work</a></li>
  <li><a href="#acknowledgments" id="toc-acknowledgments" class="nav-link" data-scroll-target="#acknowledgments">Acknowledgments</a></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references">References</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<div class="quarto-title-block"><div><h1 class="title">Visualizing Resonant Modes with Time-Averaged ESPI</h1><button type="button" class="btn code-tools-button" id="quarto-code-tools-source"><i class="bi"></i> Code</button></div></div>
<p class="subtitle lead">Metal Hemisphere, Viola, and Drumhead</p>
  <div class="quarto-categories">
    <div class="quarto-category">Experimental physics</div>
    <div class="quarto-category">Optics</div>
    <div class="quarto-category">Vibration</div>
    <div class="quarto-category">LabVIEW</div>
  </div>
  </div>

<div>
  <div class="description">
    Summer 2025 research at Whitman College — imaging the vibration modes of a metal hemisphere, a viola, and a drumhead with electronic speckle pattern interferometry.
  </div>
</div>


<div class="quarto-title-meta">

    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">August 4, 2025</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<p><strong>Takahiro Hikida</strong> | Advisor: Dr.&nbsp;Kurt Hoffman<br> Summer Research, Department of Physics, Whitman College · June–August 2025</p>
<section id="abstract" class="level2">
<h2 class="anchored" data-anchor-id="abstract">Abstract</h2>
<p>Electronic speckle pattern interferometry (ESPI) was used to image the vibration patterns of acoustically driven objects of increasing size and complexity: a metal plate (system characterization), a metal hemisphere, the top plate of a viola, a snare drumhead, and, as a preliminary test, a piano soundboard. Before imaging, I characterized the setup by bounding the laser coherence length, calibrating the reference-mirror piezo, and estimating the piezo drive from the optimum condition <span class="math inline">\(\gamma T = 2.32\)</span> derived by Moore and Skubal. The hemisphere showed nine resonances between 64 and 1614 Hz, and five of the six resonances seen in both mounting orientations agreed within 3 Hz. Where measured resonances could be matched to a finite-element (COMSOL) model, the four highest agreed within 10%, while the lowest shell mode differed by 78%. The viola produced visible patterns at every frequency from about 200 to 1000 Hz, with stronger responses near nine frequencies, and changing the bridge tension produced no reproducible frequency shift. The drumhead required drive amplitudes near 0.1 V and showed asymmetric modes, consistent with non-uniform head tension.</p>
<div class="ja">
<p>電子スペックルパターン干渉法（ESPI）を用いて、音響的に加振した物体の振動パターンを、 サイズと複雑さの順に可視化しました。対象は金属板（装置の特性評価）、金属半球、 ヴィオラの表板、スネアドラムのヘッド、そして予備実験としてピアノの響板です。 撮像の前に、レーザーのコヒーレンス長の下限を見積もり、参照ミラーのピエゾを較正し、 Moore と Skubal が導いた最適条件 <span class="math inline">\(\gamma T = 2.32\)</span> からピエゾの駆動条件を見積もりました。 半球では 64–1614 Hz に 9 つの共振が見られ、2 通りの設置で共通して観測された 6 つのうち 5 つは 3 Hz 以内で一致しました。有限要素（COMSOL）モデルと対応づけられた共振のうち、高次の 4 つは 10% 以内で一致した一方、最低次のシェルモードは 78% ずれていました。 ヴィオラでは約 200–1000 Hz のすべての周波数でパターンが見え、特に 9 つの周波数付近で強く応答しました。 駒の張力を変えても、再現性のある周波数シフトは見られませんでした。 ドラムヘッドは 0.1 V 前後の弱い駆動が必要で、非対称なモードを示しました。これはヘッドの張力が不均一であることと整合します。</p>
</div>
</section>
<section id="background-and-objectives" class="level2">
<h2 class="anchored" data-anchor-id="background-and-objectives">1. Background and Objectives</h2>
<p>In ESPI, light scattered from a rough object surface (object beam) interferes with a reference beam on a camera sensor, producing a speckle pattern. The setup used here follows the method of Moore and Skubal [2]: two frames are recorded while the object vibrates and are subtracted. A reference mirror driven by a piezo at constant speed adds a linear phase drift between the frames. In the subtracted image, stationary (nodal) regions appear bright, and vibrating regions appear as dark contours of equal amplitude, so the mode shape becomes visible.</p>
<p>The objectives of this project were:</p>
<ul>
<li>to understand which experimental parameters control image contrast and to set them quantitatively;</li>
<li>to image the resonant modes of objects that differ in stiffness, size, and shape;</li>
<li>to compare measured hemisphere resonances with a finite-element model and identify the limits of the setup.</li>
</ul>
</section>
<section id="experimental-setup-and-system-characterization" class="level2">
<h2 class="anchored" data-anchor-id="experimental-setup-and-system-characterization">2. Experimental Setup and System Characterization</h2>
<section id="optical-layout" class="level3">
<h3 class="anchored" data-anchor-id="optical-layout">2.1 Optical layout</h3>
<p>Imaging used a red laser (<span class="math inline">\(\lambda \approx 633\)</span> nm), and a green laser (<span class="math inline">\(\lambda = 532\)</span> nm) was used only to calibrate the piezo (Section 2.3). The laser output was split into two paths. The object beam was spread by a ground-glass diffuser to illuminate the object. The reference beam was reflected by a mirror mounted on a piezoelectric actuator and spread by a second diffuser before reaching the camera. A loudspeaker drove the object at a set frequency. Beam intensities were balanced using the live camera readout in NI MAX, typically by adjusting the reference beam. The camera aperture was 9.5 mm. On 15 July the original laser was replaced with a higher-power red laser of the same wavelength, which was used for the later viola, drumhead, and piano measurements.</p>
</section>
<section id="coherence-length" class="level3">
<h3 class="anchored" data-anchor-id="coherence-length">2.2 Coherence length</h3>
<p>Because the hemisphere, viola, and piano produce large differences between object and reference path lengths, I checked how much path difference the laser tolerates. Interference fringes remained visible with an object arm of about 1.00 m and a reference arm of about 3.49 m. The relevant quantity is the path <em>difference</em>, about 2.49 m, so the coherence length of the red imaging laser is at least about 2.5 m. This is much larger than the path differences in the later measurements, and fringes were in fact obtained on both the near and far surfaces of the tilted hemisphere.</p>
</section>
<section id="piezo-calibration" class="level3">
<h3 class="anchored" data-anchor-id="piezo-calibration">2.3 Piezo calibration</h3>
<p>The piezo displacement per volt was found with the green 532 nm laser by counting fringe cycles in the interference pattern while changing the voltage. One full fringe cycle corresponds to a mirror displacement of <span class="math inline">\(\lambda/2 = 266\)</span> nm, because the reflected path changes by twice the displacement. <a href="#tbl-piezo" class="quarto-xref">Table&nbsp;1</a> summarizes the measurements.</p>
<div id="tbl-piezo" class="quarto-float quarto-figure quarto-figure-center anchored" data-tbl-colwidths="[12,63,25]">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-piezo-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;1: Voltage required for one fringe cycle (<span class="math inline">\(\lambda/2 = 266\)</span> nm displacement, green laser).
</figcaption>
<div aria-describedby="tbl-piezo-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 12%">
<col style="width: 63%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>Date</th>
<th>Method</th>
<th>Voltage per fringe cycle</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>12 Jun</td>
<td>Automatic voltage ramp; tracked the center of the fringe pattern</td>
<td>6.43 V</td>
</tr>
<tr class="even">
<td>13 Jun</td>
<td>Manual offset steps; tracked positions of fringe lines; mean of several cycles</td>
<td>4.625 V</td>
</tr>
<tr class="odd">
<td>16 Jun</td>
<td>Replaced function generator; 4 cycles over a 20 V range; two trials</td>
<td>4.575 V, 4.60 V</td>
</tr>
<tr class="even">
<td>17 Jun</td>
<td>Second (round) piezo; 8 cycles over a 20 V range</td>
<td>2.29 V</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>The 6.43 V value was not reproduced after the function generator was replaced, so the 16 June value was adopted for the original piezo: <span class="math inline">\(\alpha = 266\ \text{nm} / 4.575\ \text{V} \approx 58.1\)</span> nm/V. Because <span class="math inline">\(\alpha\)</span> is a property of the piezo, not of the light, the same value applies when imaging with the red laser. The main difficulty was slow drift of the fringe pattern, which I attributed to temperature changes along the beam path.</p>
</section>
<section id="choosing-the-piezo-drive" class="level3">
<h3 class="anchored" data-anchor-id="choosing-the-piezo-drive">2.4 Choosing the piezo drive</h3>
<p>Moore and Skubal [2] show that, for a reference phase that drifts linearly at rate <span class="math inline">\(\gamma\)</span> during an exposure of length <span class="math inline">\(T\)</span>, the brightness of nodal regions is maximized at <span class="math inline">\(\gamma T = 2.32\)</span>, with a broad usable range on either side. For a mirror moving at speed <span class="math inline">\(v\)</span>,</p>
<p><span id="eq-drift"><span class="math display">\[
\gamma = 2kv, \qquad k = \frac{2\pi}{\lambda}, \qquad \gamma T = 2.32
\tag{1}\]</span></span></p>
<p>The piezo was driven with a triangle wave of peak-to-peak voltage <span class="math inline">\(V_{pp}\)</span> and full period <span class="math inline">\(T'\)</span>. The mirror travels <span class="math inline">\(\alpha V_{pp}\)</span> in each half period, so <span class="math inline">\(v = 2\alpha V_{pp}/T'\)</span>. Substituting into <a href="#eq-drift" class="quarto-xref">Equation&nbsp;1</a> gives</p>
<p><span id="eq-voltage"><span class="math display">\[
V_{pp} = \frac{2.32\, \lambda T'}{8\pi \alpha T}
\tag{2}\]</span></span></p>
<p><a href="#eq-voltage" class="quarto-xref">Equation&nbsp;2</a> depends only on the ratio <span class="math inline">\(T'/T\)</span>, so fixing the modulation period as a multiple of the exposure time makes the optimal voltage independent of exposure. With <span class="math inline">\(\lambda = 633\)</span> nm and <span class="math inline">\(\alpha = 58.1\)</span> nm/V, <a href="#eq-voltage" class="quarto-xref">Equation&nbsp;2</a> predicts <span class="math inline">\(V_{pp} \approx 4.0\)</span> V for <span class="math inline">\(T' = 4T\)</span> and <span class="math inline">\(V_{pp} \approx 2.0\)</span> V for <span class="math inline">\(T' = 2T\)</span>.</p>
<p>Experimentally, the <span class="math inline">\(T' = 2T\)</span> configuration gave the brightest fringes near 4 V, about twice the prediction, and remained usable for exposure times from 0.0313 to 0.125 s. The <span class="math inline">\(T' = 4T\)</span> configuration gave inconsistent results: its best voltage changed with exposure time and with which pair of stored frames was subtracted. All later measurements used <span class="math inline">\(T' = 2T\)</span> with a drive of 4–4.5 V, chosen empirically. Possible reasons for the factor-of-two difference are discussed in Section 4. (My original notebook calculation used <span class="math inline">\(v = \alpha V_{pp}/T'\)</span>, which omits the factor of 2 and happened to reproduce the observed 4 V.)</p>
</section>
</section>
<section id="results" class="level2">
<h2 class="anchored" data-anchor-id="results">3. Results</h2>
<section id="metal-hemisphere" class="level3">
<h3 class="anchored" data-anchor-id="metal-hemisphere">3.1 Metal hemisphere</h3>
<p>The hemisphere was first mounted with its flat face up and imaged from the side (<a href="#fig-hemi-vertical" class="quarto-xref">Figure&nbsp;1</a>). Because this view shows only the near surface, I then tilted it so that the inner and outer surfaces were both visible. A tilt of about 45° showed only two modes; a tilt of about 20° reproduced most of the resonances (<a href="#fig-hemi-tilted" class="quarto-xref">Figure&nbsp;2</a>). Settings were <span class="math inline">\(T' = 2T\)</span>, a 4–4.5 V piezo drive, and an exposure time of 0.125 s.</p>
<div id="fig-hemi-vertical" class="quarto-layout-panel">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-hemi-vertical-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 33.3%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="espi-resonant-modes/hemi-vertical-064.png" class="img-fluid figure-img"></p>
<figcaption>64.0 Hz</figcaption>
</figure>
</div>
</div>
<div class="quarto-layout-cell" style="flex-basis: 33.3%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="espi-resonant-modes/hemi-vertical-171.png" class="img-fluid figure-img"></p>
<figcaption>170.6 Hz</figcaption>
</figure>
</div>
</div>
<div class="quarto-layout-cell" style="flex-basis: 33.3%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="espi-resonant-modes/hemi-vertical-322.png" class="img-fluid figure-img"></p>
<figcaption>321.6 Hz</figcaption>
</figure>
</div>
</div>
</div>
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 33.3%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="espi-resonant-modes/hemi-vertical-505.png" class="img-fluid figure-img"></p>
<figcaption>504.5 Hz</figcaption>
</figure>
</div>
</div>
<div class="quarto-layout-cell" style="flex-basis: 33.3%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="espi-resonant-modes/hemi-vertical-730.png" class="img-fluid figure-img"></p>
<figcaption>730.3 Hz</figcaption>
</figure>
</div>
</div>
<div class="quarto-layout-cell" style="flex-basis: 33.3%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="espi-resonant-modes/hemi-vertical-738.png" class="img-fluid figure-img"></p>
<figcaption>737.5 Hz</figcaption>
</figure>
</div>
</div>
</div>
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 33.3%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="espi-resonant-modes/hemi-vertical-990.png" class="img-fluid figure-img"></p>
<figcaption>990.2 Hz</figcaption>
</figure>
</div>
</div>
<div class="quarto-layout-cell" style="flex-basis: 33.3%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="espi-resonant-modes/hemi-vertical-1301.png" class="img-fluid figure-img"></p>
<figcaption>1300.5 Hz</figcaption>
</figure>
</div>
</div>
<div class="quarto-layout-cell" style="flex-basis: 33.3%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="espi-resonant-modes/hemi-vertical-1615.png" class="img-fluid figure-img"></p>
<figcaption>1614.5 Hz</figcaption>
</figure>
</div>
</div>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-hemi-vertical-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1: Hemisphere resonances, vertical mounting.
</figcaption>
</figure>
</div>
<div id="fig-hemi-tilted" class="quarto-layout-panel">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-hemi-tilted-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 33.3%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="espi-resonant-modes/hemi-tilted-064.png" class="img-fluid figure-img"></p>
<figcaption>63.5 Hz</figcaption>
</figure>
</div>
</div>
<div class="quarto-layout-cell" style="flex-basis: 33.3%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="espi-resonant-modes/hemi-tilted-311.png" class="img-fluid figure-img"></p>
<figcaption>311.4 Hz</figcaption>
</figure>
</div>
</div>
<div class="quarto-layout-cell" style="flex-basis: 33.3%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="espi-resonant-modes/hemi-tilted-508.png" class="img-fluid figure-img"></p>
<figcaption>507.6 Hz</figcaption>
</figure>
</div>
</div>
</div>
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 33.3%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="espi-resonant-modes/hemi-tilted-730.png" class="img-fluid figure-img"></p>
<figcaption>730.2 Hz</figcaption>
</figure>
</div>
</div>
<div class="quarto-layout-cell" style="flex-basis: 33.3%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="espi-resonant-modes/hemi-tilted-990.png" class="img-fluid figure-img"></p>
<figcaption>989.9 Hz</figcaption>
</figure>
</div>
</div>
<div class="quarto-layout-cell" style="flex-basis: 33.3%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="espi-resonant-modes/hemi-tilted-1300.png" class="img-fluid figure-img"></p>
<figcaption>1299.5 Hz</figcaption>
</figure>
</div>
</div>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-hemi-tilted-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2: Hemisphere resonances, tilted about 20° so that both surfaces are visible.
</figcaption>
</figure>
</div>
<p>On 7 July I measured the frequency range over which each pattern stayed visible. The ranges were 1.7 to 13.4 Hz wide, so the measured frequencies should be read as accurate to a few hertz, not to 0.1 Hz. Ranges wider than 10 Hz may contain two overlapping modes; for example, the 730.3 and 737.5 Hz patterns may be one mode or a pair split by small asymmetries of the shell.</p>
<p><strong>Comparison with a finite-element model.</strong> Ellie St.&nbsp;Pierre built a COMSOL eigenfrequency model of the hemisphere (selected mode shapes in <a href="#fig-model" class="quarto-xref">Figure&nbsp;3</a>). <a href="#tbl-hemi" class="quarto-xref">Table&nbsp;2</a> lists the model frequencies alongside the measurements, matched by mode shape as in our model-versus-image comparison document.</p>
<div id="fig-model" class="quarto-layout-panel">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-model-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 33.3%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="espi-resonant-modes/model-061.png" class="img-fluid figure-img"></p>
<figcaption>60.7 Hz (pair 60.67 / 60.71)</figcaption>
</figure>
</div>
</div>
<div class="quarto-layout-cell" style="flex-basis: 33.3%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="espi-resonant-modes/model-096.png" class="img-fluid figure-img"></p>
<figcaption>95.7 Hz</figcaption>
</figure>
</div>
</div>
<div class="quarto-layout-cell" style="flex-basis: 33.3%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="espi-resonant-modes/model-410.png" class="img-fluid figure-img"></p>
<figcaption>409.5 Hz (axial motion)</figcaption>
</figure>
</div>
</div>
</div>
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 33.3%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="espi-resonant-modes/model-709.png" class="img-fluid figure-img"></p>
<figcaption>709.3 Hz</figcaption>
</figure>
</div>
</div>
<div class="quarto-layout-cell" style="flex-basis: 33.3%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="espi-resonant-modes/model-1021.png" class="img-fluid figure-img"></p>
<figcaption>1021.4 Hz</figcaption>
</figure>
</div>
</div>
<div class="quarto-layout-cell" style="flex-basis: 33.3%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="espi-resonant-modes/model-1378.png" class="img-fluid figure-img"></p>
<figcaption>1378.0 Hz</figcaption>
</figure>
</div>
</div>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-model-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;3: COMSOL eigenmodes of the hemisphere (model by Ellie St.&nbsp;Pierre). Color shows total displacement.
</figcaption>
</figure>
</div>
<div id="tbl-hemi" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-hemi-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;2: Measured resonances and COMSOL eigenfrequencies. Diff. = (vertical − model) / model.
</figcaption>
<div aria-describedby="tbl-hemi-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 20%">
<col style="width: 25%">
<col style="width: 31%">
<col style="width: 12%">
<col style="width: 10%">
</colgroup>
<thead>
<tr class="header">
<th>Model (Hz)</th>
<th>Vertical (Hz)</th>
<th>Tilted ~20° (Hz)</th>
<th>Diff.</th>
<th>Note</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>60.67 / 60.71</td>
<td>64.0</td>
<td>63.5</td>
<td>+5.5%</td>
<td>Near-degenerate pair</td>
</tr>
<tr class="even">
<td>95.7</td>
<td>170.6</td>
<td>—</td>
<td>+78%</td>
<td>Paired by shape; largest mismatch</td>
</tr>
<tr class="odd">
<td>235.5</td>
<td>—</td>
<td>—</td>
<td></td>
<td>Not identified</td>
</tr>
<tr class="even">
<td>—</td>
<td>321.6</td>
<td>311.4</td>
<td></td>
<td>No model mode assigned</td>
</tr>
<tr class="odd">
<td>409.5</td>
<td>—</td>
<td>—</td>
<td></td>
<td>Whole bowl moving axially; not observed</td>
</tr>
<tr class="even">
<td>445.6</td>
<td>504.5</td>
<td>507.6</td>
<td>+13.2%</td>
<td></td>
</tr>
<tr class="odd">
<td>695.8</td>
<td>—</td>
<td>—</td>
<td></td>
<td>Motion only at attachment; not expected to be visible</td>
</tr>
<tr class="even">
<td>709.3</td>
<td>730.3 (737.5)</td>
<td>730.2</td>
<td>+3.0%</td>
<td></td>
</tr>
<tr class="odd">
<td>1021.4</td>
<td>990.2</td>
<td>989.9</td>
<td>−3.1%</td>
<td></td>
</tr>
<tr class="even">
<td>1378.0</td>
<td>1300.5</td>
<td>1299.5</td>
<td>−5.6%</td>
<td></td>
</tr>
<tr class="odd">
<td>1775.2</td>
<td>1614.5</td>
<td>—</td>
<td>−9.1%</td>
<td></td>
</tr>
<tr class="even">
<td>2210.9</td>
<td>—</td>
<td>—</td>
<td></td>
<td>Not observed</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>Above 700 Hz the model and measurement agree within 10%. Across all matched shell modes, however, the difference decreases steadily with frequency, from +78% to +13.2%, +3.0%, −3.1%, −5.6%, and −9.1%. A single error in a material constant would shift all frequencies by the same ratio, so this systematic trend suggests a difference in geometry or mounting between the model and the real hemisphere, with the low-order modes most sensitive to how the hemisphere is attached. This interpretation has not been tested. The 321.6 Hz resonance has no assigned model counterpart. The axial mode at 409.5 Hz, which the model predicts could be seen in a tilted geometry, was not observed. The full side-by-side comparison is available <a href="https://docs.google.com/document/d/1FwbeYv0UMGcwDgmw2n5k4-XLW7mxpoIujZBjByzLFFA/edit?tab=t.0">here</a>.</p>
</section>
<section id="viola" class="level3">
<h3 class="anchored" data-anchor-id="viola">3.2 Viola</h3>
<p>The viola is much larger than the hemisphere, which caused two problems. First, the diffused reference beam was brightest at its center, so only the middle of the body showed fringes. Moving the reference diffuser farther from the camera spread the beam more evenly. Second, with the wider field the object beam became too weak relative to the reference beam; moving the viola and the piezo mirror back rebalanced the intensities while keeping the beams coherent.</p>
<p>Unlike the hemisphere, the viola showed a pattern at every drive frequency, starting at about 200 Hz. I scanned 200–1000 Hz in 10 Hz steps and then rescanned around frequencies with a strong response. Frequencies with a clearly strong response were near 220, 260, 360, 390, 440, 570, 650, 685, and 800 Hz, each uncertain by about ±5 Hz because of the 10 Hz step. After the laser upgrade, averaging several frames clearly improved contrast (<a href="#fig-viola" class="quarto-xref">Figure&nbsp;4</a>). The measured frequencies mostly matched an unpublished dataset recorded in the lab on the same instrument in 2024, with a few frequencies found in only one of the two datasets.</p>
<div id="fig-viola" class="quarto-layout-panel">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-viola-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 33.3%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="espi-resonant-modes/viola-210.png" class="img-fluid figure-img"></p>
<figcaption>210 Hz</figcaption>
</figure>
</div>
</div>
<div class="quarto-layout-cell" style="flex-basis: 33.3%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="espi-resonant-modes/viola-440.png" class="img-fluid figure-img"></p>
<figcaption>440 Hz</figcaption>
</figure>
</div>
</div>
<div class="quarto-layout-cell" style="flex-basis: 33.3%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="espi-resonant-modes/viola-670.png" class="img-fluid figure-img"></p>
<figcaption>670 Hz</figcaption>
</figure>
</div>
</div>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-viola-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;4: Viola top plate at three drive frequencies (higher-power laser, frame averaging). 440 Hz is one of the strong resonances listed in the text; 210 and 670 Hz show the pattern at frequencies between them.
</figcaption>
</figure>
</div>
<p><strong>Effect of bridge tension.</strong> After changing the tension on the bridge, a first scan suggested a small decrease in the mode frequencies, but a full repeat scan showed no shift for any observable mode. Bridge tension therefore had no effect detectable at this frequency resolution, consistent with the earlier measurement in the lab.</p>
</section>
<section id="drumhead" class="level3">
<h3 class="anchored" data-anchor-id="drumhead">3.3 Drumhead</h3>
<p>The snare drum was held between two optical posts, with a cushion to reduce vibration transmitted from the table (<a href="#fig-drum-tension" class="quarto-xref">Figure&nbsp;6</a>, left). This clamps the shell from the side and may slightly alter the boundary condition, but it was stable enough to image.</p>
<p>At first only the nodal outline near the rim was visible and the center was dark. The cause was overdriving: the membrane is much less stiff than the other objects, so at the original speaker level its amplitude was large enough that the fringes near the center were too dense to resolve. Lowering the speaker drive to about 0.1 V or less made the patterns visible. Too little drive, however, let the fundamental-mode pattern (60 Hz), which appeared at every drive frequency, dominate the image, so the drive had to be balanced between the two. In one session the patterns were clearer with the piezo switched off, possibly because this suppressed the fundamental-mode background.</p>
<p>Seven modes were found in total; six are shown in <a href="#fig-drum" class="quarto-xref">Figure&nbsp;5</a>. None was axially symmetric, and the patterns became more complex at higher frequency. The asymmetry is consistent with non-uniform tension across the head (an interpretation, not tested directly).</p>
<div id="fig-drum" class="quarto-layout-panel">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-drum-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 33.3%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="espi-resonant-modes/drum-fundamental.jpg" class="img-fluid figure-img"></p>
<figcaption>60 Hz (fundamental)</figcaption>
</figure>
</div>
</div>
<div class="quarto-layout-cell" style="flex-basis: 33.3%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="espi-resonant-modes/drum-115.jpg" class="img-fluid figure-img"></p>
<figcaption>114.8 Hz</figcaption>
</figure>
</div>
</div>
<div class="quarto-layout-cell" style="flex-basis: 33.3%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="espi-resonant-modes/drum-155.jpg" class="img-fluid figure-img"></p>
<figcaption>155.4 Hz</figcaption>
</figure>
</div>
</div>
</div>
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 33.3%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="espi-resonant-modes/drum-177.jpg" class="img-fluid figure-img"></p>
<figcaption>176.8 Hz</figcaption>
</figure>
</div>
</div>
<div class="quarto-layout-cell" style="flex-basis: 33.3%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="espi-resonant-modes/drum-210.jpg" class="img-fluid figure-img"></p>
<figcaption>210.3 Hz</figcaption>
</figure>
</div>
</div>
<div class="quarto-layout-cell" style="flex-basis: 33.3%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="espi-resonant-modes/drum-251.jpg" class="img-fluid figure-img"></p>
<figcaption>250.7 Hz</figcaption>
</figure>
</div>
</div>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-drum-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;5: Drumhead modes.
</figcaption>
</figure>
</div>
<p><strong>Effect of tension.</strong> Loosening the two upper tension screws shifted the center of the fundamental-mode pattern toward the loosened screws (<a href="#fig-drum-tension" class="quarto-xref">Figure&nbsp;6</a>, right), showing directly that uneven tension breaks the symmetry of the mode.</p>
<div id="fig-drum-tension" class="quarto-layout-panel">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-drum-tension-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="espi-resonant-modes/drum-mounting.jpg" class="img-fluid figure-img"></p>
<figcaption>Mounting (cushion circled)</figcaption>
</figure>
</div>
</div>
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="espi-resonant-modes/drum-loosened.jpg" class="img-fluid figure-img"></p>
<figcaption>Fundamental, two upper screws loosened</figcaption>
</figure>
</div>
</div>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-drum-tension-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;6: Drum mounting and the tension test.
</figcaption>
</figure>
</div>
<p>All drumhead images: <a href="https://drive.google.com/drive/folders/1X4MxfZjFVEiNugM8Fy3t4Fd4ph9sKtA5">image folder</a>. Viola images: <a href="https://drive.google.com/drive/folders/1fSnSLAet4q3R7I2JZGuUH-cxnDZsEqQi">image folder</a>.</p>
</section>
<section id="piano-soundboard-preliminary" class="level3">
<h3 class="anchored" data-anchor-id="piano-soundboard-preliminary">3.4 Piano soundboard (preliminary)</h3>
<p>In the final two weeks, Ethan Hawkins and I moved the laser and camera onto a portable ESPI system and transported it to the music building. Specular reflection from the center of the soundboard saturated the camera and darkened the rest of the image; tilting the piano moved the reflection out of the field of view. Scanning 100–320 Hz with a 0.625 s exposure and five-frame averaging produced visible patterns at several frequencies. A repeat measurement on 4 August gave darker images that could not be corrected by rebalancing the beams, so the piano results remain preliminary.</p>
</section>
</section>
<section id="discussion" class="level2">
<h2 class="anchored" data-anchor-id="discussion">4. Discussion</h2>
<p>Four practical points determined image quality across all objects:</p>
<ul>
<li><strong>Beam balance.</strong> Contrast was best with matched beam intensities. On the viola I initially assumed the object beam was the stronger one; measuring showed the opposite, so the weaker beam should be identified by measurement, not by assumption.</li>
<li><strong>Drive amplitude vs.&nbsp;stiffness.</strong> Stiff objects (plate, hemisphere) needed strong drive, while the drumhead needed roughly 0.1 V. Overdriving hides the mode rather than enhancing it.</li>
<li><strong>Phase modulation.</strong> Fixing <span class="math inline">\(T'\)</span> as a multiple of the exposure time made the optimal piezo voltage independent of exposure (<a href="#eq-voltage" class="quarto-xref">Equation&nbsp;2</a>).</li>
<li><strong>Averaging.</strong> Averaging frames greatly improved contrast, but only when the pattern was stable between frames.</li>
</ul>
<p><strong>Open question: the piezo drive.</strong> The best observed drive was about twice the value predicted by <a href="#eq-voltage" class="quarto-xref">Equation&nbsp;2</a>. Three explanations seem plausible but have not been tested. First, the theory assumes the two subtracted frames are recorded back to back; if the frames are separated by a delay <span class="math inline">\(T_0\)</span>, the phase step between them becomes <span class="math inline">\(\gamma T_0\)</span> (Eq. 21 of [2]). The software subtracted frames stored in buffers 0 and 3 rather than adjacent frames, and the optimum voltage did change when other buffer pairs were used. Second, with <span class="math inline">\(T'\)</span> only two to four times the exposure, the triangle wave reverses direction during or between exposures, so the mirror speed is not constant as the theory assumes. Third, the calibration was quasi-static, while the piezo was driven at several hertz during imaging. A direct test would be to measure nodal-region brightness versus <span class="math inline">\(V_{pp}\)</span> for adjacent-frame subtraction and compare it with Fig. 5 of [2].</p>
<p>Other limitations are that all results are qualitative images, that frequencies were identified by eye with an uncertainty set by the resonance width or scan step (a few hertz), and that one hemisphere resonance (321.6 Hz) is not yet matched to the model.</p>
</section>
<section id="future-work" class="level2">
<h2 class="anchored" data-anchor-id="future-work">5. Future Work</h2>
<ul>
<li>Measure nodal brightness versus piezo voltage with adjacent-frame subtraction to resolve the factor-of-two discrepancy in Section 2.4.</li>
<li>Quantitative fringe analysis: extract the fringe order in small image regions to estimate vibration amplitude.</li>
<li>Assign the 321.6 Hz hemisphere resonance by counting nodal lines, and refine the model geometry and mount to explain the frequency-dependent mismatch.</li>
<li>Tension the drumhead uniformly with a tension gauge, test whether symmetric modes appear, and then vary tension in controlled steps.</li>
<li>Complete narrow-band scans of the piano soundboard around the resonances found in the broad scan.</li>
</ul>
</section>
<section id="acknowledgments" class="level2">
<h2 class="anchored" data-anchor-id="acknowledgments">Acknowledgments</h2>
<p>I thank Dr.&nbsp;Kurt Hoffman for supervision and guidance, Ellie St.&nbsp;Pierre for the COMSOL model of the hemisphere, and Ethan Hawkins for collaboration on the measurements.</p>
</section>
<section id="references" class="level2">
<h2 class="anchored" data-anchor-id="references">References</h2>
<ol type="1">
<li>M. C. Horne, “Measuring Resonances of Guitar Top Plates at Various Stages of Fabrication,” senior thesis, Whitman College (2022).</li>
<li>T. R. Moore and J. J. Skubal, “Time-averaged electronic speckle pattern interferometry in the presence of ambient motion. Part I. Theory and experiments,” <em>Applied Optics</em> 47(25), 4640–4648 (2008). <a href="https://doi.org/10.1364/AO.47.004640">doi:10.1364/AO.47.004640</a></li>
</ol>


<!-- -->

</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
    const viewSource = window.document.getElementById('quarto-view-source') ||
                       window.document.getElementById('quarto-code-tools-source');
    if (viewSource) {
      const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
      viewSource.addEventListener("click", function(e) {
        if (sourceUrl) {
          // rstudio viewer pane
          if (/\bcapabilities=\b/.test(window.location)) {
            window.open(sourceUrl);
          } else {
            window.location.href = sourceUrl;
          }
        } else {
          const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
          modal.show();
        }
        return false;
      });
    }
    function toggleCodeHandler(show) {
      return function(e) {
        const cellDetails = window.document.querySelectorAll(".cell details.code-fold");
        for (let i=0; i<cellDetails.length; i++) {
          const details = cellDetails[i];
          if (show) {
            details.open = true;
          } else {
            details.removeAttribute("open");
          }
        }
        const cellCodeDivs = window.document.querySelectorAll(".cell div.sourceCode.cell-code");
        const fromCls = show ? "hidden" : "unhidden";
        const toCls = show ? "unhidden" : "hidden";
        for (let i=0; i<cellCodeDivs.length; i++) {
          const codeDiv = cellCodeDivs[i];
          if (codeDiv.classList.contains(fromCls)) {
            codeDiv.classList.remove(fromCls);
            codeDiv.classList.add(toCls);
          } 
        }
        return false;
      }
    }
    const hideAllCode = window.document.getElementById("quarto-hide-all-code");
    if (hideAllCode) {
      hideAllCode.addEventListener("click", toggleCodeHandler(false));
    }
    const showAllCode = window.document.getElementById("quarto-show-all-code");
    if (showAllCode) {
      showAllCode.addEventListener("click", toggleCodeHandler(true));
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/takahiro-h16\.github\.io");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script><div class="modal fade" id="quarto-embedded-source-code-modal" tabindex="-1" aria-labelledby="quarto-embedded-source-code-modal-label" aria-hidden="true"><div class="modal-dialog modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" id="quarto-embedded-source-code-modal-label">Source Code</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb1" data-shortcodes="false"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="an">title:</span><span class="co"> "Visualizing Resonant Modes with Time-Averaged ESPI"</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="an">subtitle:</span><span class="co"> "Metal Hemisphere, Viola, and Drumhead"</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="an">description:</span><span class="co"> "Summer 2025 research at Whitman College — imaging the vibration modes of a metal hemisphere, a viola, and a drumhead with electronic speckle pattern interferometry."</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="an">date:</span><span class="co"> 2025-08-04</span></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="an">categories:</span><span class="co"> [Experimental physics, Optics, Vibration, LabVIEW]</span></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="an">image:</span><span class="co"> espi-resonant-modes/hemi-vertical-990.png</span></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>**Takahiro Hikida** | Advisor: Dr. Kurt Hoffman<span class="dt">&lt;</span><span class="kw">br</span><span class="dt">&gt;</span></span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a>Summer Research, Department of Physics, Whitman College · June–August 2025</span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a><span class="fu">## Abstract</span></span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a>Electronic speckle pattern interferometry (ESPI) was used to image the vibration</span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a>patterns of acoustically driven objects of increasing size and complexity: a metal</span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a>plate (system characterization), a metal hemisphere, the top plate of a viola, a</span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a>snare drumhead, and, as a preliminary test, a piano soundboard. Before imaging, I</span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a>characterized the setup by bounding the laser coherence length, calibrating the</span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a>reference-mirror piezo, and estimating the piezo drive from the optimum condition</span>
<span id="cb1-21"><a href="#cb1-21" aria-hidden="true" tabindex="-1"></a>$\gamma T = 2.32$ derived by Moore and Skubal. The hemisphere showed nine</span>
<span id="cb1-22"><a href="#cb1-22" aria-hidden="true" tabindex="-1"></a>resonances between 64 and 1614 Hz, and five of the six resonances seen in both</span>
<span id="cb1-23"><a href="#cb1-23" aria-hidden="true" tabindex="-1"></a>mounting orientations agreed within 3 Hz. Where measured resonances could be</span>
<span id="cb1-24"><a href="#cb1-24" aria-hidden="true" tabindex="-1"></a>matched to a finite-element (COMSOL) model, the four highest agreed within 10%,</span>
<span id="cb1-25"><a href="#cb1-25" aria-hidden="true" tabindex="-1"></a>while the lowest shell mode differed by 78%. The viola produced visible patterns at</span>
<span id="cb1-26"><a href="#cb1-26" aria-hidden="true" tabindex="-1"></a>every frequency from about 200 to 1000 Hz, with stronger responses near nine</span>
<span id="cb1-27"><a href="#cb1-27" aria-hidden="true" tabindex="-1"></a>frequencies, and changing the bridge tension produced no reproducible frequency</span>
<span id="cb1-28"><a href="#cb1-28" aria-hidden="true" tabindex="-1"></a>shift. The drumhead required drive amplitudes near 0.1 V and showed asymmetric</span>
<span id="cb1-29"><a href="#cb1-29" aria-hidden="true" tabindex="-1"></a>modes, consistent with non-uniform head tension.</span>
<span id="cb1-30"><a href="#cb1-30" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-31"><a href="#cb1-31" aria-hidden="true" tabindex="-1"></a>::: {.ja}</span>
<span id="cb1-32"><a href="#cb1-32" aria-hidden="true" tabindex="-1"></a>電子スペックルパターン干渉法（ESPI）を用いて、音響的に加振した物体の振動パターンを、</span>
<span id="cb1-33"><a href="#cb1-33" aria-hidden="true" tabindex="-1"></a>サイズと複雑さの順に可視化しました。対象は金属板（装置の特性評価）、金属半球、</span>
<span id="cb1-34"><a href="#cb1-34" aria-hidden="true" tabindex="-1"></a>ヴィオラの表板、スネアドラムのヘッド、そして予備実験としてピアノの響板です。</span>
<span id="cb1-35"><a href="#cb1-35" aria-hidden="true" tabindex="-1"></a>撮像の前に、レーザーのコヒーレンス長の下限を見積もり、参照ミラーのピエゾを較正し、</span>
<span id="cb1-36"><a href="#cb1-36" aria-hidden="true" tabindex="-1"></a>Moore と Skubal が導いた最適条件 $\gamma T = 2.32$ からピエゾの駆動条件を見積もりました。</span>
<span id="cb1-37"><a href="#cb1-37" aria-hidden="true" tabindex="-1"></a>半球では 64–1614 Hz に 9 つの共振が見られ、2 通りの設置で共通して観測された 6 つのうち 5 つは</span>
<span id="cb1-38"><a href="#cb1-38" aria-hidden="true" tabindex="-1"></a>3 Hz 以内で一致しました。有限要素（COMSOL）モデルと対応づけられた共振のうち、高次の 4 つは</span>
<span id="cb1-39"><a href="#cb1-39" aria-hidden="true" tabindex="-1"></a>10% 以内で一致した一方、最低次のシェルモードは 78% ずれていました。</span>
<span id="cb1-40"><a href="#cb1-40" aria-hidden="true" tabindex="-1"></a>ヴィオラでは約 200–1000 Hz のすべての周波数でパターンが見え、特に 9 つの周波数付近で強く応答しました。</span>
<span id="cb1-41"><a href="#cb1-41" aria-hidden="true" tabindex="-1"></a>駒の張力を変えても、再現性のある周波数シフトは見られませんでした。</span>
<span id="cb1-42"><a href="#cb1-42" aria-hidden="true" tabindex="-1"></a>ドラムヘッドは 0.1 V 前後の弱い駆動が必要で、非対称なモードを示しました。これはヘッドの張力が不均一であることと整合します。</span>
<span id="cb1-43"><a href="#cb1-43" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb1-44"><a href="#cb1-44" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-45"><a href="#cb1-45" aria-hidden="true" tabindex="-1"></a><span class="fu">## 1. Background and Objectives</span></span>
<span id="cb1-46"><a href="#cb1-46" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-47"><a href="#cb1-47" aria-hidden="true" tabindex="-1"></a>In ESPI, light scattered from a rough object surface (object beam) interferes with</span>
<span id="cb1-48"><a href="#cb1-48" aria-hidden="true" tabindex="-1"></a>a reference beam on a camera sensor, producing a speckle pattern. The setup used</span>
<span id="cb1-49"><a href="#cb1-49" aria-hidden="true" tabindex="-1"></a>here follows the method of Moore and Skubal <span class="co">[</span><span class="ot">2</span><span class="co">]</span>: two frames are recorded while the</span>
<span id="cb1-50"><a href="#cb1-50" aria-hidden="true" tabindex="-1"></a>object vibrates and are subtracted. A reference mirror driven by a piezo at</span>
<span id="cb1-51"><a href="#cb1-51" aria-hidden="true" tabindex="-1"></a>constant speed adds a linear phase drift between the frames. In the subtracted</span>
<span id="cb1-52"><a href="#cb1-52" aria-hidden="true" tabindex="-1"></a>image, stationary (nodal) regions appear bright, and vibrating regions appear as</span>
<span id="cb1-53"><a href="#cb1-53" aria-hidden="true" tabindex="-1"></a>dark contours of equal amplitude, so the mode shape becomes visible.</span>
<span id="cb1-54"><a href="#cb1-54" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-55"><a href="#cb1-55" aria-hidden="true" tabindex="-1"></a>The objectives of this project were:</span>
<span id="cb1-56"><a href="#cb1-56" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-57"><a href="#cb1-57" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>to understand which experimental parameters control image contrast and to set</span>
<span id="cb1-58"><a href="#cb1-58" aria-hidden="true" tabindex="-1"></a>  them quantitatively;</span>
<span id="cb1-59"><a href="#cb1-59" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>to image the resonant modes of objects that differ in stiffness, size, and shape;</span>
<span id="cb1-60"><a href="#cb1-60" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>to compare measured hemisphere resonances with a finite-element model and</span>
<span id="cb1-61"><a href="#cb1-61" aria-hidden="true" tabindex="-1"></a>  identify the limits of the setup.</span>
<span id="cb1-62"><a href="#cb1-62" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-63"><a href="#cb1-63" aria-hidden="true" tabindex="-1"></a><span class="fu">## 2. Experimental Setup and System Characterization</span></span>
<span id="cb1-64"><a href="#cb1-64" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-65"><a href="#cb1-65" aria-hidden="true" tabindex="-1"></a><span class="fu">### 2.1 Optical layout</span></span>
<span id="cb1-66"><a href="#cb1-66" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-67"><a href="#cb1-67" aria-hidden="true" tabindex="-1"></a>Imaging used a red laser ($\lambda \approx 633$ nm), and a green laser</span>
<span id="cb1-68"><a href="#cb1-68" aria-hidden="true" tabindex="-1"></a>($\lambda = 532$ nm) was used only to calibrate the piezo (Section 2.3). The laser</span>
<span id="cb1-69"><a href="#cb1-69" aria-hidden="true" tabindex="-1"></a>output was split into two paths. The object beam was spread by a ground-glass</span>
<span id="cb1-70"><a href="#cb1-70" aria-hidden="true" tabindex="-1"></a>diffuser to illuminate the object. The reference beam was reflected by a mirror</span>
<span id="cb1-71"><a href="#cb1-71" aria-hidden="true" tabindex="-1"></a>mounted on a piezoelectric actuator and spread by a second diffuser before</span>
<span id="cb1-72"><a href="#cb1-72" aria-hidden="true" tabindex="-1"></a>reaching the camera. A loudspeaker drove the object at a set frequency. Beam</span>
<span id="cb1-73"><a href="#cb1-73" aria-hidden="true" tabindex="-1"></a>intensities were balanced using the live camera readout in NI MAX, typically by</span>
<span id="cb1-74"><a href="#cb1-74" aria-hidden="true" tabindex="-1"></a>adjusting the reference beam. The camera aperture was 9.5 mm. On 15 July the</span>
<span id="cb1-75"><a href="#cb1-75" aria-hidden="true" tabindex="-1"></a>original laser was replaced with a higher-power red laser of the same wavelength,</span>
<span id="cb1-76"><a href="#cb1-76" aria-hidden="true" tabindex="-1"></a>which was used for the later viola, drumhead, and piano measurements.</span>
<span id="cb1-77"><a href="#cb1-77" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-78"><a href="#cb1-78" aria-hidden="true" tabindex="-1"></a><span class="fu">### 2.2 Coherence length</span></span>
<span id="cb1-79"><a href="#cb1-79" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-80"><a href="#cb1-80" aria-hidden="true" tabindex="-1"></a>Because the hemisphere, viola, and piano produce large differences between object</span>
<span id="cb1-81"><a href="#cb1-81" aria-hidden="true" tabindex="-1"></a>and reference path lengths, I checked how much path difference the laser</span>
<span id="cb1-82"><a href="#cb1-82" aria-hidden="true" tabindex="-1"></a>tolerates. Interference fringes remained visible with an object arm of about 1.00 m</span>
<span id="cb1-83"><a href="#cb1-83" aria-hidden="true" tabindex="-1"></a>and a reference arm of about 3.49 m. The relevant quantity is the path</span>
<span id="cb1-84"><a href="#cb1-84" aria-hidden="true" tabindex="-1"></a>*difference*, about 2.49 m, so the coherence length of the red imaging laser is at</span>
<span id="cb1-85"><a href="#cb1-85" aria-hidden="true" tabindex="-1"></a>least about 2.5 m. This is much larger than the path differences in the later</span>
<span id="cb1-86"><a href="#cb1-86" aria-hidden="true" tabindex="-1"></a>measurements, and fringes were in fact obtained on both the near and far surfaces</span>
<span id="cb1-87"><a href="#cb1-87" aria-hidden="true" tabindex="-1"></a>of the tilted hemisphere.</span>
<span id="cb1-88"><a href="#cb1-88" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-89"><a href="#cb1-89" aria-hidden="true" tabindex="-1"></a><span class="fu">### 2.3 Piezo calibration</span></span>
<span id="cb1-90"><a href="#cb1-90" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-91"><a href="#cb1-91" aria-hidden="true" tabindex="-1"></a>The piezo displacement per volt was found with the green 532 nm laser by counting</span>
<span id="cb1-92"><a href="#cb1-92" aria-hidden="true" tabindex="-1"></a>fringe cycles in the interference pattern while changing the voltage. One full</span>
<span id="cb1-93"><a href="#cb1-93" aria-hidden="true" tabindex="-1"></a>fringe cycle corresponds to a mirror displacement of $\lambda/2 = 266$ nm, because</span>
<span id="cb1-94"><a href="#cb1-94" aria-hidden="true" tabindex="-1"></a>the reflected path changes by twice the displacement. @tbl-piezo summarizes the</span>
<span id="cb1-95"><a href="#cb1-95" aria-hidden="true" tabindex="-1"></a>measurements.</span>
<span id="cb1-96"><a href="#cb1-96" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-97"><a href="#cb1-97" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Date <span class="pp">|</span> Method <span class="pp">|</span> Voltage per fringe cycle <span class="pp">|</span></span>
<span id="cb1-98"><a href="#cb1-98" aria-hidden="true" tabindex="-1"></a><span class="pp">|------|--------|--------------------------|</span></span>
<span id="cb1-99"><a href="#cb1-99" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> 12 Jun <span class="pp">|</span> Automatic voltage ramp; tracked the center of the fringe pattern <span class="pp">|</span> 6.43 V <span class="pp">|</span></span>
<span id="cb1-100"><a href="#cb1-100" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> 13 Jun <span class="pp">|</span> Manual offset steps; tracked positions of fringe lines; mean of several cycles <span class="pp">|</span> 4.625 V <span class="pp">|</span></span>
<span id="cb1-101"><a href="#cb1-101" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> 16 Jun <span class="pp">|</span> Replaced function generator; 4 cycles over a 20 V range; two trials <span class="pp">|</span> 4.575 V, 4.60 V <span class="pp">|</span></span>
<span id="cb1-102"><a href="#cb1-102" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> 17 Jun <span class="pp">|</span> Second (round) piezo; 8 cycles over a 20 V range <span class="pp">|</span> 2.29 V <span class="pp">|</span></span>
<span id="cb1-103"><a href="#cb1-103" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-104"><a href="#cb1-104" aria-hidden="true" tabindex="-1"></a>: Voltage required for one fringe cycle ($\lambda/2 = 266$ nm displacement, green laser). {#tbl-piezo tbl-colwidths="<span class="co">[</span><span class="ot">12,63,25</span><span class="co">]</span>"}</span>
<span id="cb1-105"><a href="#cb1-105" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-106"><a href="#cb1-106" aria-hidden="true" tabindex="-1"></a>The 6.43 V value was not reproduced after the function generator was replaced, so</span>
<span id="cb1-107"><a href="#cb1-107" aria-hidden="true" tabindex="-1"></a>the 16 June value was adopted for the original piezo:</span>
<span id="cb1-108"><a href="#cb1-108" aria-hidden="true" tabindex="-1"></a>$\alpha = 266\ \text{nm} / 4.575\ \text{V} \approx 58.1$ nm/V. Because $\alpha$ is</span>
<span id="cb1-109"><a href="#cb1-109" aria-hidden="true" tabindex="-1"></a>a property of the piezo, not of the light, the same value applies when imaging</span>
<span id="cb1-110"><a href="#cb1-110" aria-hidden="true" tabindex="-1"></a>with the red laser. The main difficulty was slow drift of the fringe pattern,</span>
<span id="cb1-111"><a href="#cb1-111" aria-hidden="true" tabindex="-1"></a>which I attributed to temperature changes along the beam path.</span>
<span id="cb1-112"><a href="#cb1-112" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-113"><a href="#cb1-113" aria-hidden="true" tabindex="-1"></a><span class="fu">### 2.4 Choosing the piezo drive</span></span>
<span id="cb1-114"><a href="#cb1-114" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-115"><a href="#cb1-115" aria-hidden="true" tabindex="-1"></a>Moore and Skubal <span class="co">[</span><span class="ot">2</span><span class="co">]</span> show that, for a reference phase that drifts linearly at rate</span>
<span id="cb1-116"><a href="#cb1-116" aria-hidden="true" tabindex="-1"></a>$\gamma$ during an exposure of length $T$, the brightness of nodal regions is</span>
<span id="cb1-117"><a href="#cb1-117" aria-hidden="true" tabindex="-1"></a>maximized at $\gamma T = 2.32$, with a broad usable range on either side. For a</span>
<span id="cb1-118"><a href="#cb1-118" aria-hidden="true" tabindex="-1"></a>mirror moving at speed $v$,</span>
<span id="cb1-119"><a href="#cb1-119" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-120"><a href="#cb1-120" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb1-121"><a href="#cb1-121" aria-hidden="true" tabindex="-1"></a>\gamma = 2kv, \qquad k = \frac{2\pi}{\lambda}, \qquad \gamma T = 2.32</span>
<span id="cb1-122"><a href="#cb1-122" aria-hidden="true" tabindex="-1"></a>$$ {#eq-drift}</span>
<span id="cb1-123"><a href="#cb1-123" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-124"><a href="#cb1-124" aria-hidden="true" tabindex="-1"></a>The piezo was driven with a triangle wave of peak-to-peak voltage $V_{pp}$ and full</span>
<span id="cb1-125"><a href="#cb1-125" aria-hidden="true" tabindex="-1"></a>period $T'$. The mirror travels $\alpha V_{pp}$ in each half period, so</span>
<span id="cb1-126"><a href="#cb1-126" aria-hidden="true" tabindex="-1"></a>$v = 2\alpha V_{pp}/T'$. Substituting into @eq-drift gives</span>
<span id="cb1-127"><a href="#cb1-127" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-128"><a href="#cb1-128" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb1-129"><a href="#cb1-129" aria-hidden="true" tabindex="-1"></a>V_{pp} = \frac{2.32\, \lambda T'}{8\pi \alpha T}</span>
<span id="cb1-130"><a href="#cb1-130" aria-hidden="true" tabindex="-1"></a>$$ {#eq-voltage}</span>
<span id="cb1-131"><a href="#cb1-131" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-132"><a href="#cb1-132" aria-hidden="true" tabindex="-1"></a>@eq-voltage depends only on the ratio $T'/T$, so fixing the modulation period as a</span>
<span id="cb1-133"><a href="#cb1-133" aria-hidden="true" tabindex="-1"></a>multiple of the exposure time makes the optimal voltage independent of exposure.</span>
<span id="cb1-134"><a href="#cb1-134" aria-hidden="true" tabindex="-1"></a>With $\lambda = 633$ nm and $\alpha = 58.1$ nm/V, @eq-voltage predicts</span>
<span id="cb1-135"><a href="#cb1-135" aria-hidden="true" tabindex="-1"></a>$V_{pp} \approx 4.0$ V for $T' = 4T$ and $V_{pp} \approx 2.0$ V for $T' = 2T$.</span>
<span id="cb1-136"><a href="#cb1-136" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-137"><a href="#cb1-137" aria-hidden="true" tabindex="-1"></a>Experimentally, the $T' = 2T$ configuration gave the brightest fringes near 4 V,</span>
<span id="cb1-138"><a href="#cb1-138" aria-hidden="true" tabindex="-1"></a>about twice the prediction, and remained usable for exposure times from 0.0313 to</span>
<span id="cb1-139"><a href="#cb1-139" aria-hidden="true" tabindex="-1"></a>0.125 s. The $T' = 4T$ configuration gave inconsistent results: its best voltage</span>
<span id="cb1-140"><a href="#cb1-140" aria-hidden="true" tabindex="-1"></a>changed with exposure time and with which pair of stored frames was subtracted.</span>
<span id="cb1-141"><a href="#cb1-141" aria-hidden="true" tabindex="-1"></a>All later measurements used $T' = 2T$ with a drive of 4–4.5 V, chosen empirically.</span>
<span id="cb1-142"><a href="#cb1-142" aria-hidden="true" tabindex="-1"></a>Possible reasons for the factor-of-two difference are discussed in Section 4. (My</span>
<span id="cb1-143"><a href="#cb1-143" aria-hidden="true" tabindex="-1"></a>original notebook calculation used $v = \alpha V_{pp}/T'$, which omits the factor</span>
<span id="cb1-144"><a href="#cb1-144" aria-hidden="true" tabindex="-1"></a>of 2 and happened to reproduce the observed 4 V.)</span>
<span id="cb1-145"><a href="#cb1-145" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-146"><a href="#cb1-146" aria-hidden="true" tabindex="-1"></a><span class="fu">## 3. Results</span></span>
<span id="cb1-147"><a href="#cb1-147" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-148"><a href="#cb1-148" aria-hidden="true" tabindex="-1"></a><span class="fu">### 3.1 Metal hemisphere</span></span>
<span id="cb1-149"><a href="#cb1-149" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-150"><a href="#cb1-150" aria-hidden="true" tabindex="-1"></a>The hemisphere was first mounted with its flat face up and imaged from the side</span>
<span id="cb1-151"><a href="#cb1-151" aria-hidden="true" tabindex="-1"></a>(@fig-hemi-vertical). Because this view shows only the near surface, I then tilted</span>
<span id="cb1-152"><a href="#cb1-152" aria-hidden="true" tabindex="-1"></a>it so that the inner and outer surfaces were both visible. A tilt of about 45°</span>
<span id="cb1-153"><a href="#cb1-153" aria-hidden="true" tabindex="-1"></a>showed only two modes; a tilt of about 20° reproduced most of the resonances</span>
<span id="cb1-154"><a href="#cb1-154" aria-hidden="true" tabindex="-1"></a>(@fig-hemi-tilted). Settings were $T' = 2T$, a 4–4.5 V piezo drive, and an</span>
<span id="cb1-155"><a href="#cb1-155" aria-hidden="true" tabindex="-1"></a>exposure time of 0.125 s.</span>
<span id="cb1-156"><a href="#cb1-156" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-157"><a href="#cb1-157" aria-hidden="true" tabindex="-1"></a>::: {#fig-hemi-vertical layout-ncol=3}</span>
<span id="cb1-158"><a href="#cb1-158" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-159"><a href="#cb1-159" aria-hidden="true" tabindex="-1"></a><span class="al">![64.0 Hz](espi-resonant-modes/hemi-vertical-064.png)</span></span>
<span id="cb1-160"><a href="#cb1-160" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-161"><a href="#cb1-161" aria-hidden="true" tabindex="-1"></a><span class="al">![170.6 Hz](espi-resonant-modes/hemi-vertical-171.png)</span></span>
<span id="cb1-162"><a href="#cb1-162" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-163"><a href="#cb1-163" aria-hidden="true" tabindex="-1"></a><span class="al">![321.6 Hz](espi-resonant-modes/hemi-vertical-322.png)</span></span>
<span id="cb1-164"><a href="#cb1-164" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-165"><a href="#cb1-165" aria-hidden="true" tabindex="-1"></a><span class="al">![504.5 Hz](espi-resonant-modes/hemi-vertical-505.png)</span></span>
<span id="cb1-166"><a href="#cb1-166" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-167"><a href="#cb1-167" aria-hidden="true" tabindex="-1"></a><span class="al">![730.3 Hz](espi-resonant-modes/hemi-vertical-730.png)</span></span>
<span id="cb1-168"><a href="#cb1-168" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-169"><a href="#cb1-169" aria-hidden="true" tabindex="-1"></a><span class="al">![737.5 Hz](espi-resonant-modes/hemi-vertical-738.png)</span></span>
<span id="cb1-170"><a href="#cb1-170" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-171"><a href="#cb1-171" aria-hidden="true" tabindex="-1"></a><span class="al">![990.2 Hz](espi-resonant-modes/hemi-vertical-990.png)</span></span>
<span id="cb1-172"><a href="#cb1-172" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-173"><a href="#cb1-173" aria-hidden="true" tabindex="-1"></a><span class="al">![1300.5 Hz](espi-resonant-modes/hemi-vertical-1301.png)</span></span>
<span id="cb1-174"><a href="#cb1-174" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-175"><a href="#cb1-175" aria-hidden="true" tabindex="-1"></a><span class="al">![1614.5 Hz](espi-resonant-modes/hemi-vertical-1615.png)</span></span>
<span id="cb1-176"><a href="#cb1-176" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-177"><a href="#cb1-177" aria-hidden="true" tabindex="-1"></a>Hemisphere resonances, vertical mounting.</span>
<span id="cb1-178"><a href="#cb1-178" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb1-179"><a href="#cb1-179" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-180"><a href="#cb1-180" aria-hidden="true" tabindex="-1"></a>::: {#fig-hemi-tilted layout-ncol=3}</span>
<span id="cb1-181"><a href="#cb1-181" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-182"><a href="#cb1-182" aria-hidden="true" tabindex="-1"></a><span class="al">![63.5 Hz](espi-resonant-modes/hemi-tilted-064.png)</span></span>
<span id="cb1-183"><a href="#cb1-183" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-184"><a href="#cb1-184" aria-hidden="true" tabindex="-1"></a><span class="al">![311.4 Hz](espi-resonant-modes/hemi-tilted-311.png)</span></span>
<span id="cb1-185"><a href="#cb1-185" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-186"><a href="#cb1-186" aria-hidden="true" tabindex="-1"></a><span class="al">![507.6 Hz](espi-resonant-modes/hemi-tilted-508.png)</span></span>
<span id="cb1-187"><a href="#cb1-187" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-188"><a href="#cb1-188" aria-hidden="true" tabindex="-1"></a><span class="al">![730.2 Hz](espi-resonant-modes/hemi-tilted-730.png)</span></span>
<span id="cb1-189"><a href="#cb1-189" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-190"><a href="#cb1-190" aria-hidden="true" tabindex="-1"></a><span class="al">![989.9 Hz](espi-resonant-modes/hemi-tilted-990.png)</span></span>
<span id="cb1-191"><a href="#cb1-191" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-192"><a href="#cb1-192" aria-hidden="true" tabindex="-1"></a><span class="al">![1299.5 Hz](espi-resonant-modes/hemi-tilted-1300.png)</span></span>
<span id="cb1-193"><a href="#cb1-193" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-194"><a href="#cb1-194" aria-hidden="true" tabindex="-1"></a>Hemisphere resonances, tilted about 20° so that both surfaces are visible.</span>
<span id="cb1-195"><a href="#cb1-195" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb1-196"><a href="#cb1-196" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-197"><a href="#cb1-197" aria-hidden="true" tabindex="-1"></a>On 7 July I measured the frequency range over which each pattern stayed visible.</span>
<span id="cb1-198"><a href="#cb1-198" aria-hidden="true" tabindex="-1"></a>The ranges were 1.7 to 13.4 Hz wide, so the measured frequencies should be read as</span>
<span id="cb1-199"><a href="#cb1-199" aria-hidden="true" tabindex="-1"></a>accurate to a few hertz, not to 0.1 Hz. Ranges wider than 10 Hz may contain two</span>
<span id="cb1-200"><a href="#cb1-200" aria-hidden="true" tabindex="-1"></a>overlapping modes; for example, the 730.3 and 737.5 Hz patterns may be one mode or</span>
<span id="cb1-201"><a href="#cb1-201" aria-hidden="true" tabindex="-1"></a>a pair split by small asymmetries of the shell.</span>
<span id="cb1-202"><a href="#cb1-202" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-203"><a href="#cb1-203" aria-hidden="true" tabindex="-1"></a>**Comparison with a finite-element model.** Ellie St. Pierre built a COMSOL</span>
<span id="cb1-204"><a href="#cb1-204" aria-hidden="true" tabindex="-1"></a>eigenfrequency model of the hemisphere (selected mode shapes in @fig-model).</span>
<span id="cb1-205"><a href="#cb1-205" aria-hidden="true" tabindex="-1"></a>@tbl-hemi lists the model frequencies alongside the measurements, matched by mode</span>
<span id="cb1-206"><a href="#cb1-206" aria-hidden="true" tabindex="-1"></a>shape as in our model-versus-image comparison document.</span>
<span id="cb1-207"><a href="#cb1-207" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-208"><a href="#cb1-208" aria-hidden="true" tabindex="-1"></a>::: {#fig-model layout-ncol=3}</span>
<span id="cb1-209"><a href="#cb1-209" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-210"><a href="#cb1-210" aria-hidden="true" tabindex="-1"></a><span class="al">![60.7 Hz (pair 60.67 / 60.71)](espi-resonant-modes/model-061.png)</span></span>
<span id="cb1-211"><a href="#cb1-211" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-212"><a href="#cb1-212" aria-hidden="true" tabindex="-1"></a><span class="al">![95.7 Hz](espi-resonant-modes/model-096.png)</span></span>
<span id="cb1-213"><a href="#cb1-213" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-214"><a href="#cb1-214" aria-hidden="true" tabindex="-1"></a><span class="al">![409.5 Hz (axial motion)](espi-resonant-modes/model-410.png)</span></span>
<span id="cb1-215"><a href="#cb1-215" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-216"><a href="#cb1-216" aria-hidden="true" tabindex="-1"></a><span class="al">![709.3 Hz](espi-resonant-modes/model-709.png)</span></span>
<span id="cb1-217"><a href="#cb1-217" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-218"><a href="#cb1-218" aria-hidden="true" tabindex="-1"></a><span class="al">![1021.4 Hz](espi-resonant-modes/model-1021.png)</span></span>
<span id="cb1-219"><a href="#cb1-219" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-220"><a href="#cb1-220" aria-hidden="true" tabindex="-1"></a><span class="al">![1378.0 Hz](espi-resonant-modes/model-1378.png)</span></span>
<span id="cb1-221"><a href="#cb1-221" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-222"><a href="#cb1-222" aria-hidden="true" tabindex="-1"></a>COMSOL eigenmodes of the hemisphere (model by Ellie St. Pierre). Color shows total displacement.</span>
<span id="cb1-223"><a href="#cb1-223" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb1-224"><a href="#cb1-224" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-225"><a href="#cb1-225" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Model (Hz) <span class="pp">|</span> Vertical (Hz) <span class="pp">|</span> Tilted ~20° (Hz) <span class="pp">|</span> Diff. <span class="pp">|</span> Note <span class="pp">|</span></span>
<span id="cb1-226"><a href="#cb1-226" aria-hidden="true" tabindex="-1"></a><span class="pp">|------------|---------------|------------------|-------|------|</span></span>
<span id="cb1-227"><a href="#cb1-227" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> 60.67 / 60.71 <span class="pp">|</span> 64.0 <span class="pp">|</span> 63.5 <span class="pp">|</span> +5.5% <span class="pp">|</span> Near-degenerate pair <span class="pp">|</span></span>
<span id="cb1-228"><a href="#cb1-228" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> 95.7 <span class="pp">|</span> 170.6 <span class="pp">|</span> — <span class="pp">|</span> +78% <span class="pp">|</span> Paired by shape; largest mismatch <span class="pp">|</span></span>
<span id="cb1-229"><a href="#cb1-229" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> 235.5 <span class="pp">|</span> — <span class="pp">|</span> — <span class="pp">|</span> <span class="pp">|</span> Not identified <span class="pp">|</span></span>
<span id="cb1-230"><a href="#cb1-230" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> — <span class="pp">|</span> 321.6 <span class="pp">|</span> 311.4 <span class="pp">|</span> <span class="pp">|</span> No model mode assigned <span class="pp">|</span></span>
<span id="cb1-231"><a href="#cb1-231" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> 409.5 <span class="pp">|</span> — <span class="pp">|</span> — <span class="pp">|</span> <span class="pp">|</span> Whole bowl moving axially; not observed <span class="pp">|</span></span>
<span id="cb1-232"><a href="#cb1-232" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> 445.6 <span class="pp">|</span> 504.5 <span class="pp">|</span> 507.6 <span class="pp">|</span> +13.2% <span class="pp">|</span> <span class="pp">|</span></span>
<span id="cb1-233"><a href="#cb1-233" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> 695.8 <span class="pp">|</span> — <span class="pp">|</span> — <span class="pp">|</span> <span class="pp">|</span> Motion only at attachment; not expected to be visible <span class="pp">|</span></span>
<span id="cb1-234"><a href="#cb1-234" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> 709.3 <span class="pp">|</span> 730.3 (737.5) <span class="pp">|</span> 730.2 <span class="pp">|</span> +3.0% <span class="pp">|</span> <span class="pp">|</span></span>
<span id="cb1-235"><a href="#cb1-235" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> 1021.4 <span class="pp">|</span> 990.2 <span class="pp">|</span> 989.9 <span class="pp">|</span> −3.1% <span class="pp">|</span> <span class="pp">|</span></span>
<span id="cb1-236"><a href="#cb1-236" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> 1378.0 <span class="pp">|</span> 1300.5 <span class="pp">|</span> 1299.5 <span class="pp">|</span> −5.6% <span class="pp">|</span> <span class="pp">|</span></span>
<span id="cb1-237"><a href="#cb1-237" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> 1775.2 <span class="pp">|</span> 1614.5 <span class="pp">|</span> — <span class="pp">|</span> −9.1% <span class="pp">|</span> <span class="pp">|</span></span>
<span id="cb1-238"><a href="#cb1-238" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> 2210.9 <span class="pp">|</span> — <span class="pp">|</span> — <span class="pp">|</span> <span class="pp">|</span> Not observed <span class="pp">|</span></span>
<span id="cb1-239"><a href="#cb1-239" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-240"><a href="#cb1-240" aria-hidden="true" tabindex="-1"></a>: Measured resonances and COMSOL eigenfrequencies. Diff. = (vertical − model) / model. {#tbl-hemi}</span>
<span id="cb1-241"><a href="#cb1-241" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-242"><a href="#cb1-242" aria-hidden="true" tabindex="-1"></a>Above 700 Hz the model and measurement agree within 10%. Across all matched shell</span>
<span id="cb1-243"><a href="#cb1-243" aria-hidden="true" tabindex="-1"></a>modes, however, the difference decreases steadily with frequency, from +78% to</span>
<span id="cb1-244"><a href="#cb1-244" aria-hidden="true" tabindex="-1"></a>+13.2%, +3.0%, −3.1%, −5.6%, and −9.1%. A single error in a material constant</span>
<span id="cb1-245"><a href="#cb1-245" aria-hidden="true" tabindex="-1"></a>would shift all frequencies by the same ratio, so this systematic trend suggests a</span>
<span id="cb1-246"><a href="#cb1-246" aria-hidden="true" tabindex="-1"></a>difference in geometry or mounting between the model and the real hemisphere, with</span>
<span id="cb1-247"><a href="#cb1-247" aria-hidden="true" tabindex="-1"></a>the low-order modes most sensitive to how the hemisphere is attached. This</span>
<span id="cb1-248"><a href="#cb1-248" aria-hidden="true" tabindex="-1"></a>interpretation has not been tested. The 321.6 Hz resonance has no assigned model</span>
<span id="cb1-249"><a href="#cb1-249" aria-hidden="true" tabindex="-1"></a>counterpart. The axial mode at 409.5 Hz, which the model predicts could be seen in</span>
<span id="cb1-250"><a href="#cb1-250" aria-hidden="true" tabindex="-1"></a>a tilted geometry, was not observed. The full side-by-side comparison is available</span>
<span id="cb1-251"><a href="#cb1-251" aria-hidden="true" tabindex="-1"></a><span class="co">[</span><span class="ot">here</span><span class="co">](https://docs.google.com/document/d/1FwbeYv0UMGcwDgmw2n5k4-XLW7mxpoIujZBjByzLFFA/edit?tab=t.0)</span>.</span>
<span id="cb1-252"><a href="#cb1-252" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-253"><a href="#cb1-253" aria-hidden="true" tabindex="-1"></a><span class="fu">### 3.2 Viola</span></span>
<span id="cb1-254"><a href="#cb1-254" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-255"><a href="#cb1-255" aria-hidden="true" tabindex="-1"></a>The viola is much larger than the hemisphere, which caused two problems. First,</span>
<span id="cb1-256"><a href="#cb1-256" aria-hidden="true" tabindex="-1"></a>the diffused reference beam was brightest at its center, so only the middle of the</span>
<span id="cb1-257"><a href="#cb1-257" aria-hidden="true" tabindex="-1"></a>body showed fringes. Moving the reference diffuser farther from the camera spread</span>
<span id="cb1-258"><a href="#cb1-258" aria-hidden="true" tabindex="-1"></a>the beam more evenly. Second, with the wider field the object beam became too weak</span>
<span id="cb1-259"><a href="#cb1-259" aria-hidden="true" tabindex="-1"></a>relative to the reference beam; moving the viola and the piezo mirror back</span>
<span id="cb1-260"><a href="#cb1-260" aria-hidden="true" tabindex="-1"></a>rebalanced the intensities while keeping the beams coherent.</span>
<span id="cb1-261"><a href="#cb1-261" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-262"><a href="#cb1-262" aria-hidden="true" tabindex="-1"></a>Unlike the hemisphere, the viola showed a pattern at every drive frequency,</span>
<span id="cb1-263"><a href="#cb1-263" aria-hidden="true" tabindex="-1"></a>starting at about 200 Hz. I scanned 200–1000 Hz in 10 Hz steps and then rescanned</span>
<span id="cb1-264"><a href="#cb1-264" aria-hidden="true" tabindex="-1"></a>around frequencies with a strong response. Frequencies with a clearly strong</span>
<span id="cb1-265"><a href="#cb1-265" aria-hidden="true" tabindex="-1"></a>response were near 220, 260, 360, 390, 440, 570, 650, 685, and 800 Hz, each</span>
<span id="cb1-266"><a href="#cb1-266" aria-hidden="true" tabindex="-1"></a>uncertain by about ±5 Hz because of the 10 Hz step. After the laser upgrade,</span>
<span id="cb1-267"><a href="#cb1-267" aria-hidden="true" tabindex="-1"></a>averaging several frames clearly improved contrast (@fig-viola). The measured</span>
<span id="cb1-268"><a href="#cb1-268" aria-hidden="true" tabindex="-1"></a>frequencies mostly matched an unpublished dataset recorded in the lab on the same</span>
<span id="cb1-269"><a href="#cb1-269" aria-hidden="true" tabindex="-1"></a>instrument in 2024, with a few frequencies found in only one of the two datasets.</span>
<span id="cb1-270"><a href="#cb1-270" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-271"><a href="#cb1-271" aria-hidden="true" tabindex="-1"></a>::: {#fig-viola layout-ncol=3}</span>
<span id="cb1-272"><a href="#cb1-272" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-273"><a href="#cb1-273" aria-hidden="true" tabindex="-1"></a><span class="al">![210 Hz](espi-resonant-modes/viola-210.png)</span></span>
<span id="cb1-274"><a href="#cb1-274" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-275"><a href="#cb1-275" aria-hidden="true" tabindex="-1"></a><span class="al">![440 Hz](espi-resonant-modes/viola-440.png)</span></span>
<span id="cb1-276"><a href="#cb1-276" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-277"><a href="#cb1-277" aria-hidden="true" tabindex="-1"></a><span class="al">![670 Hz](espi-resonant-modes/viola-670.png)</span></span>
<span id="cb1-278"><a href="#cb1-278" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-279"><a href="#cb1-279" aria-hidden="true" tabindex="-1"></a>Viola top plate at three drive frequencies (higher-power laser, frame averaging). 440 Hz is one of the strong resonances listed in the text; 210 and 670 Hz show the pattern at frequencies between them.</span>
<span id="cb1-280"><a href="#cb1-280" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb1-281"><a href="#cb1-281" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-282"><a href="#cb1-282" aria-hidden="true" tabindex="-1"></a>**Effect of bridge tension.** After changing the tension on the bridge, a first</span>
<span id="cb1-283"><a href="#cb1-283" aria-hidden="true" tabindex="-1"></a>scan suggested a small decrease in the mode frequencies, but a full repeat scan</span>
<span id="cb1-284"><a href="#cb1-284" aria-hidden="true" tabindex="-1"></a>showed no shift for any observable mode. Bridge tension therefore had no effect</span>
<span id="cb1-285"><a href="#cb1-285" aria-hidden="true" tabindex="-1"></a>detectable at this frequency resolution, consistent with the earlier measurement</span>
<span id="cb1-286"><a href="#cb1-286" aria-hidden="true" tabindex="-1"></a>in the lab.</span>
<span id="cb1-287"><a href="#cb1-287" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-288"><a href="#cb1-288" aria-hidden="true" tabindex="-1"></a><span class="fu">### 3.3 Drumhead</span></span>
<span id="cb1-289"><a href="#cb1-289" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-290"><a href="#cb1-290" aria-hidden="true" tabindex="-1"></a>The snare drum was held between two optical posts, with a cushion to reduce</span>
<span id="cb1-291"><a href="#cb1-291" aria-hidden="true" tabindex="-1"></a>vibration transmitted from the table (@fig-drum-tension, left). This clamps the</span>
<span id="cb1-292"><a href="#cb1-292" aria-hidden="true" tabindex="-1"></a>shell from the side and may slightly alter the boundary condition, but it was</span>
<span id="cb1-293"><a href="#cb1-293" aria-hidden="true" tabindex="-1"></a>stable enough to image.</span>
<span id="cb1-294"><a href="#cb1-294" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-295"><a href="#cb1-295" aria-hidden="true" tabindex="-1"></a>At first only the nodal outline near the rim was visible and the center was dark.</span>
<span id="cb1-296"><a href="#cb1-296" aria-hidden="true" tabindex="-1"></a>The cause was overdriving: the membrane is much less stiff than the other objects,</span>
<span id="cb1-297"><a href="#cb1-297" aria-hidden="true" tabindex="-1"></a>so at the original speaker level its amplitude was large enough that the fringes</span>
<span id="cb1-298"><a href="#cb1-298" aria-hidden="true" tabindex="-1"></a>near the center were too dense to resolve. Lowering the speaker drive to about</span>
<span id="cb1-299"><a href="#cb1-299" aria-hidden="true" tabindex="-1"></a>0.1 V or less made the patterns visible. Too little drive, however, let the</span>
<span id="cb1-300"><a href="#cb1-300" aria-hidden="true" tabindex="-1"></a>fundamental-mode pattern (60 Hz), which appeared at every drive frequency, dominate</span>
<span id="cb1-301"><a href="#cb1-301" aria-hidden="true" tabindex="-1"></a>the image, so the drive had to be balanced between the two. In one session the</span>
<span id="cb1-302"><a href="#cb1-302" aria-hidden="true" tabindex="-1"></a>patterns were clearer with the piezo switched off, possibly because this</span>
<span id="cb1-303"><a href="#cb1-303" aria-hidden="true" tabindex="-1"></a>suppressed the fundamental-mode background.</span>
<span id="cb1-304"><a href="#cb1-304" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-305"><a href="#cb1-305" aria-hidden="true" tabindex="-1"></a>Seven modes were found in total; six are shown in @fig-drum. None was axially</span>
<span id="cb1-306"><a href="#cb1-306" aria-hidden="true" tabindex="-1"></a>symmetric, and the patterns became more complex at higher frequency. The asymmetry</span>
<span id="cb1-307"><a href="#cb1-307" aria-hidden="true" tabindex="-1"></a>is consistent with non-uniform tension across the head (an interpretation, not</span>
<span id="cb1-308"><a href="#cb1-308" aria-hidden="true" tabindex="-1"></a>tested directly).</span>
<span id="cb1-309"><a href="#cb1-309" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-310"><a href="#cb1-310" aria-hidden="true" tabindex="-1"></a>::: {#fig-drum layout-ncol=3}</span>
<span id="cb1-311"><a href="#cb1-311" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-312"><a href="#cb1-312" aria-hidden="true" tabindex="-1"></a><span class="al">![60 Hz (fundamental)](espi-resonant-modes/drum-fundamental.jpg)</span></span>
<span id="cb1-313"><a href="#cb1-313" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-314"><a href="#cb1-314" aria-hidden="true" tabindex="-1"></a><span class="al">![114.8 Hz](espi-resonant-modes/drum-115.jpg)</span></span>
<span id="cb1-315"><a href="#cb1-315" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-316"><a href="#cb1-316" aria-hidden="true" tabindex="-1"></a><span class="al">![155.4 Hz](espi-resonant-modes/drum-155.jpg)</span></span>
<span id="cb1-317"><a href="#cb1-317" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-318"><a href="#cb1-318" aria-hidden="true" tabindex="-1"></a><span class="al">![176.8 Hz](espi-resonant-modes/drum-177.jpg)</span></span>
<span id="cb1-319"><a href="#cb1-319" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-320"><a href="#cb1-320" aria-hidden="true" tabindex="-1"></a><span class="al">![210.3 Hz](espi-resonant-modes/drum-210.jpg)</span></span>
<span id="cb1-321"><a href="#cb1-321" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-322"><a href="#cb1-322" aria-hidden="true" tabindex="-1"></a><span class="al">![250.7 Hz](espi-resonant-modes/drum-251.jpg)</span></span>
<span id="cb1-323"><a href="#cb1-323" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-324"><a href="#cb1-324" aria-hidden="true" tabindex="-1"></a>Drumhead modes.</span>
<span id="cb1-325"><a href="#cb1-325" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb1-326"><a href="#cb1-326" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-327"><a href="#cb1-327" aria-hidden="true" tabindex="-1"></a>**Effect of tension.** Loosening the two upper tension screws shifted the center of</span>
<span id="cb1-328"><a href="#cb1-328" aria-hidden="true" tabindex="-1"></a>the fundamental-mode pattern toward the loosened screws (@fig-drum-tension, right),</span>
<span id="cb1-329"><a href="#cb1-329" aria-hidden="true" tabindex="-1"></a>showing directly that uneven tension breaks the symmetry of the mode.</span>
<span id="cb1-330"><a href="#cb1-330" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-331"><a href="#cb1-331" aria-hidden="true" tabindex="-1"></a>::: {#fig-drum-tension layout-ncol=2}</span>
<span id="cb1-332"><a href="#cb1-332" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-333"><a href="#cb1-333" aria-hidden="true" tabindex="-1"></a><span class="al">![Mounting (cushion circled)](espi-resonant-modes/drum-mounting.jpg)</span></span>
<span id="cb1-334"><a href="#cb1-334" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-335"><a href="#cb1-335" aria-hidden="true" tabindex="-1"></a><span class="al">![Fundamental, two upper screws loosened](espi-resonant-modes/drum-loosened.jpg)</span></span>
<span id="cb1-336"><a href="#cb1-336" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-337"><a href="#cb1-337" aria-hidden="true" tabindex="-1"></a>Drum mounting and the tension test.</span>
<span id="cb1-338"><a href="#cb1-338" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb1-339"><a href="#cb1-339" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-340"><a href="#cb1-340" aria-hidden="true" tabindex="-1"></a>All drumhead images:</span>
<span id="cb1-341"><a href="#cb1-341" aria-hidden="true" tabindex="-1"></a><span class="co">[</span><span class="ot">image folder</span><span class="co">](https://drive.google.com/drive/folders/1X4MxfZjFVEiNugM8Fy3t4Fd4ph9sKtA5)</span>.</span>
<span id="cb1-342"><a href="#cb1-342" aria-hidden="true" tabindex="-1"></a>Viola images:</span>
<span id="cb1-343"><a href="#cb1-343" aria-hidden="true" tabindex="-1"></a><span class="co">[</span><span class="ot">image folder</span><span class="co">](https://drive.google.com/drive/folders/1fSnSLAet4q3R7I2JZGuUH-cxnDZsEqQi)</span>.</span>
<span id="cb1-344"><a href="#cb1-344" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-345"><a href="#cb1-345" aria-hidden="true" tabindex="-1"></a><span class="fu">### 3.4 Piano soundboard (preliminary)</span></span>
<span id="cb1-346"><a href="#cb1-346" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-347"><a href="#cb1-347" aria-hidden="true" tabindex="-1"></a>In the final two weeks, Ethan Hawkins and I moved the laser and camera onto a</span>
<span id="cb1-348"><a href="#cb1-348" aria-hidden="true" tabindex="-1"></a>portable ESPI system and transported it to the music building. Specular reflection</span>
<span id="cb1-349"><a href="#cb1-349" aria-hidden="true" tabindex="-1"></a>from the center of the soundboard saturated the camera and darkened the rest of the</span>
<span id="cb1-350"><a href="#cb1-350" aria-hidden="true" tabindex="-1"></a>image; tilting the piano moved the reflection out of the field of view. Scanning</span>
<span id="cb1-351"><a href="#cb1-351" aria-hidden="true" tabindex="-1"></a>100–320 Hz with a 0.625 s exposure and five-frame averaging produced visible</span>
<span id="cb1-352"><a href="#cb1-352" aria-hidden="true" tabindex="-1"></a>patterns at several frequencies. A repeat measurement on 4 August gave darker</span>
<span id="cb1-353"><a href="#cb1-353" aria-hidden="true" tabindex="-1"></a>images that could not be corrected by rebalancing the beams, so the piano results</span>
<span id="cb1-354"><a href="#cb1-354" aria-hidden="true" tabindex="-1"></a>remain preliminary.</span>
<span id="cb1-355"><a href="#cb1-355" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-356"><a href="#cb1-356" aria-hidden="true" tabindex="-1"></a><span class="fu">## 4. Discussion</span></span>
<span id="cb1-357"><a href="#cb1-357" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-358"><a href="#cb1-358" aria-hidden="true" tabindex="-1"></a>Four practical points determined image quality across all objects:</span>
<span id="cb1-359"><a href="#cb1-359" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-360"><a href="#cb1-360" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Beam balance.** Contrast was best with matched beam intensities. On the viola</span>
<span id="cb1-361"><a href="#cb1-361" aria-hidden="true" tabindex="-1"></a>  I initially assumed the object beam was the stronger one; measuring showed the</span>
<span id="cb1-362"><a href="#cb1-362" aria-hidden="true" tabindex="-1"></a>  opposite, so the weaker beam should be identified by measurement, not by</span>
<span id="cb1-363"><a href="#cb1-363" aria-hidden="true" tabindex="-1"></a>  assumption.</span>
<span id="cb1-364"><a href="#cb1-364" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Drive amplitude vs. stiffness.** Stiff objects (plate, hemisphere) needed</span>
<span id="cb1-365"><a href="#cb1-365" aria-hidden="true" tabindex="-1"></a>  strong drive, while the drumhead needed roughly 0.1 V. Overdriving hides the</span>
<span id="cb1-366"><a href="#cb1-366" aria-hidden="true" tabindex="-1"></a>  mode rather than enhancing it.</span>
<span id="cb1-367"><a href="#cb1-367" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Phase modulation.** Fixing $T'$ as a multiple of the exposure time made the</span>
<span id="cb1-368"><a href="#cb1-368" aria-hidden="true" tabindex="-1"></a>  optimal piezo voltage independent of exposure (@eq-voltage).</span>
<span id="cb1-369"><a href="#cb1-369" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Averaging.** Averaging frames greatly improved contrast, but only when the</span>
<span id="cb1-370"><a href="#cb1-370" aria-hidden="true" tabindex="-1"></a>  pattern was stable between frames.</span>
<span id="cb1-371"><a href="#cb1-371" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-372"><a href="#cb1-372" aria-hidden="true" tabindex="-1"></a>**Open question: the piezo drive.** The best observed drive was about twice the</span>
<span id="cb1-373"><a href="#cb1-373" aria-hidden="true" tabindex="-1"></a>value predicted by @eq-voltage. Three explanations seem plausible but have not been</span>
<span id="cb1-374"><a href="#cb1-374" aria-hidden="true" tabindex="-1"></a>tested. First, the theory assumes the two subtracted frames are recorded back to</span>
<span id="cb1-375"><a href="#cb1-375" aria-hidden="true" tabindex="-1"></a>back; if the frames are separated by a delay $T_0$, the phase step between them</span>
<span id="cb1-376"><a href="#cb1-376" aria-hidden="true" tabindex="-1"></a>becomes $\gamma T_0$ (Eq. 21 of <span class="co">[</span><span class="ot">2</span><span class="co">]</span>). The software subtracted frames stored in</span>
<span id="cb1-377"><a href="#cb1-377" aria-hidden="true" tabindex="-1"></a>buffers 0 and 3 rather than adjacent frames, and the optimum voltage did change</span>
<span id="cb1-378"><a href="#cb1-378" aria-hidden="true" tabindex="-1"></a>when other buffer pairs were used. Second, with $T'$ only two to four times the</span>
<span id="cb1-379"><a href="#cb1-379" aria-hidden="true" tabindex="-1"></a>exposure, the triangle wave reverses direction during or between exposures, so the</span>
<span id="cb1-380"><a href="#cb1-380" aria-hidden="true" tabindex="-1"></a>mirror speed is not constant as the theory assumes. Third, the calibration was</span>
<span id="cb1-381"><a href="#cb1-381" aria-hidden="true" tabindex="-1"></a>quasi-static, while the piezo was driven at several hertz during imaging. A direct</span>
<span id="cb1-382"><a href="#cb1-382" aria-hidden="true" tabindex="-1"></a>test would be to measure nodal-region brightness versus $V_{pp}$ for adjacent-frame</span>
<span id="cb1-383"><a href="#cb1-383" aria-hidden="true" tabindex="-1"></a>subtraction and compare it with Fig. 5 of <span class="co">[</span><span class="ot">2</span><span class="co">]</span>.</span>
<span id="cb1-384"><a href="#cb1-384" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-385"><a href="#cb1-385" aria-hidden="true" tabindex="-1"></a>Other limitations are that all results are qualitative images, that frequencies</span>
<span id="cb1-386"><a href="#cb1-386" aria-hidden="true" tabindex="-1"></a>were identified by eye with an uncertainty set by the resonance width or scan step</span>
<span id="cb1-387"><a href="#cb1-387" aria-hidden="true" tabindex="-1"></a>(a few hertz), and that one hemisphere resonance (321.6 Hz) is not yet matched to</span>
<span id="cb1-388"><a href="#cb1-388" aria-hidden="true" tabindex="-1"></a>the model.</span>
<span id="cb1-389"><a href="#cb1-389" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-390"><a href="#cb1-390" aria-hidden="true" tabindex="-1"></a><span class="fu">## 5. Future Work</span></span>
<span id="cb1-391"><a href="#cb1-391" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-392"><a href="#cb1-392" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Measure nodal brightness versus piezo voltage with adjacent-frame subtraction to</span>
<span id="cb1-393"><a href="#cb1-393" aria-hidden="true" tabindex="-1"></a>  resolve the factor-of-two discrepancy in Section 2.4.</span>
<span id="cb1-394"><a href="#cb1-394" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Quantitative fringe analysis: extract the fringe order in small image regions to</span>
<span id="cb1-395"><a href="#cb1-395" aria-hidden="true" tabindex="-1"></a>  estimate vibration amplitude.</span>
<span id="cb1-396"><a href="#cb1-396" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Assign the 321.6 Hz hemisphere resonance by counting nodal lines, and refine the</span>
<span id="cb1-397"><a href="#cb1-397" aria-hidden="true" tabindex="-1"></a>  model geometry and mount to explain the frequency-dependent mismatch.</span>
<span id="cb1-398"><a href="#cb1-398" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Tension the drumhead uniformly with a tension gauge, test whether symmetric</span>
<span id="cb1-399"><a href="#cb1-399" aria-hidden="true" tabindex="-1"></a>  modes appear, and then vary tension in controlled steps.</span>
<span id="cb1-400"><a href="#cb1-400" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Complete narrow-band scans of the piano soundboard around the resonances found</span>
<span id="cb1-401"><a href="#cb1-401" aria-hidden="true" tabindex="-1"></a>  in the broad scan.</span>
<span id="cb1-402"><a href="#cb1-402" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-403"><a href="#cb1-403" aria-hidden="true" tabindex="-1"></a><span class="fu">## Acknowledgments</span></span>
<span id="cb1-404"><a href="#cb1-404" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-405"><a href="#cb1-405" aria-hidden="true" tabindex="-1"></a>I thank Dr. Kurt Hoffman for supervision and guidance, Ellie St. Pierre for the</span>
<span id="cb1-406"><a href="#cb1-406" aria-hidden="true" tabindex="-1"></a>COMSOL model of the hemisphere, and Ethan Hawkins for collaboration on the</span>
<span id="cb1-407"><a href="#cb1-407" aria-hidden="true" tabindex="-1"></a>measurements.</span>
<span id="cb1-408"><a href="#cb1-408" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-409"><a href="#cb1-409" aria-hidden="true" tabindex="-1"></a><span class="fu">## References</span></span>
<span id="cb1-410"><a href="#cb1-410" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-411"><a href="#cb1-411" aria-hidden="true" tabindex="-1"></a><span class="ss">1. </span>M. C. Horne, "Measuring Resonances of Guitar Top Plates at Various Stages of</span>
<span id="cb1-412"><a href="#cb1-412" aria-hidden="true" tabindex="-1"></a>   Fabrication," senior thesis, Whitman College (2022).</span>
<span id="cb1-413"><a href="#cb1-413" aria-hidden="true" tabindex="-1"></a><span class="ss">2. </span>T. R. Moore and J. J. Skubal, "Time-averaged electronic speckle pattern</span>
<span id="cb1-414"><a href="#cb1-414" aria-hidden="true" tabindex="-1"></a>   interferometry in the presence of ambient motion. Part I. Theory and</span>
<span id="cb1-415"><a href="#cb1-415" aria-hidden="true" tabindex="-1"></a>   experiments," *Applied Optics* 47(25), 4640–4648 (2008).</span>
<span id="cb1-416"><a href="#cb1-416" aria-hidden="true" tabindex="-1"></a>   <span class="co">[</span><span class="ot">doi:10.1364/AO.47.004640</span><span class="co">](https://doi.org/10.1364/AO.47.004640)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button" data-in-quarto-modal=""><i class="bi"></i></button></div>
</div></div></div></div></div>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
      &nbsp;
    </div>   
    <div class="nav-footer-center">
<p>© 2026 Takahiro Hikida · Built with <a href="https://quarto.org">Quarto</a></p>
</div>
    <div class="nav-footer-right">
      &nbsp;
    </div>
  </div>
</footer>




</body></html>